[project]
name = "nuscope"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "crewai",
    "requests>=2.34.2",
    "streamlit>=1.63.0",
]

[tool.uv.sources]
crewai = { path = "../crewAI/lib/crewai", editable = true }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
